services:
  - type: web
    name: bestbyte-api
    runtime: docker
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: COMPANY
        value: "BestByte"
      - key: PORT
        value: 8000
      - key: FRONTEND_URL
        sync: false
      - key: ENVIRONMENT
        value: "production"
      - key: RENDER_DISK_MOUNT_PATH
        value: "/app/data"
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1